version: "3.9"

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "8000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/postgres
    volumes:
      - .:/app
