version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: development
    ports:
      - "5001:5000"
    volumes:
      - .:/app

volumes:
  pg_data:
